<?php
// Generated by Zend Framework 2
return array(
    'Proba\Controller\DeFocController'   => __DIR__ . '/src/Proba/Controller/DeFocController.php',
    'Proba\Controller\DeValorController' => __DIR__ . '/src/Proba/Controller/DeValorController.php',
);