<?php

// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Album\Module'                        => __DIR__ . '/Module.php',
    'Album\Controller\AlbumController' => __DIR__ . '/src/Album/Controller/AlbumController.php',
    'AlbumTest\Framework\TestCase'        => __DIR__ . '/tests/AlbumTest/Framework/TestCase.php',
    'AlbumTest\SampleTest'                => __DIR__ . '/tests/AlbumTest/SampleTest.php',
    'AlbumTest\Bootstrap'                => __DIR__ . '/tests/AlbumTest/Bootstrap.php',
);